print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/alejandromorales/Desktop/ZynthWave_G7/Zynthwave URP/Assets/Art/Models/Art/BruteEnemy/BruteEnemy_Model.mb"`)
{		
	file -o "/Users/alejandromorales/Desktop/ZynthWave_G7/Zynthwave URP/Assets/Art/Models/Art/BruteEnemy/BruteEnemy_Model.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/alejandromorales/Desktop/ZynthWave_G7/Zynthwave URP/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/alejandromorales/Desktop/ZynthWave_G7/Zynthwave URP/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/alejandromorales/Desktop/ZynthWave_G7/Zynthwave URP/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
